package com.love.jax.bean.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.love.jax.bean.table.county;
import com.love.jax.bean.table.province;
import com.love.jax.bean.table.city;

import com.love.jax.bean.dao.countyDao;
import com.love.jax.bean.dao.provinceDao;
import com.love.jax.bean.dao.cityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig countyDaoConfig;
    private final DaoConfig provinceDaoConfig;
    private final DaoConfig cityDaoConfig;

    private final countyDao countyDao;
    private final provinceDao provinceDao;
    private final cityDao cityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        countyDaoConfig = daoConfigMap.get(countyDao.class).clone();
        countyDaoConfig.initIdentityScope(type);

        provinceDaoConfig = daoConfigMap.get(provinceDao.class).clone();
        provinceDaoConfig.initIdentityScope(type);

        cityDaoConfig = daoConfigMap.get(cityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        countyDao = new countyDao(countyDaoConfig, this);
        provinceDao = new provinceDao(provinceDaoConfig, this);
        cityDao = new cityDao(cityDaoConfig, this);

        registerDao(county.class, countyDao);
        registerDao(province.class, provinceDao);
        registerDao(city.class, cityDao);
    }
    
    public void clear() {
        countyDaoConfig.clearIdentityScope();
        provinceDaoConfig.clearIdentityScope();
        cityDaoConfig.clearIdentityScope();
    }

    public countyDao getCountyDao() {
        return countyDao;
    }

    public provinceDao getProvinceDao() {
        return provinceDao;
    }

    public cityDao getCityDao() {
        return cityDao;
    }

}
